<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="55853" started-at="2018-05-11T13:00:33Z" finished-at="2018-05-11T13:01:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="55853" started-at="2018-05-11T13:00:33Z" finished-at="2018-05-11T13:01:28Z">
      <class name="com_Milan_Test.WPastMedicationHistoryTest">
        <test-method status="PASS" signature="Setup()[pri:0, instance:com_Milan_Test.WPastMedicationHistoryTest@5f341870]" name="Setup" is-config="true" duration-ms="51867" started-at="2018-05-11T18:30:33Z" finished-at="2018-05-11T18:31:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="pastMedicationHistorysetdataTest()[pri:3, instance:com_Milan_Test.WPastMedicationHistoryTest@5f341870]" name="pastMedicationHistorysetdataTest" duration-ms="2811" started-at="2018-05-11T18:31:24Z" finished-at="2018-05-11T18:31:27Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 3, Size: 3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com_milan_POM.WPastMedicationHistoryPage.pastMedicationHistorysetdata(WPastMedicationHistoryPage.java:122)
	at com_Milan_Test.WPastMedicationHistoryTest.pastMedicationHistorysetdataTest(WPastMedicationHistoryTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pastMedicationHistorysetdataTest -->
        <test-method status="PASS" signature="Teardown()[pri:0, instance:com_Milan_Test.WPastMedicationHistoryTest@5f341870]" name="Teardown" is-config="true" duration-ms="766" started-at="2018-05-11T18:31:28Z" finished-at="2018-05-11T18:31:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- com_Milan_Test.WPastMedicationHistoryTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
