<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="16" hostname="IVF111" name="com_Milan_Test.WAddictionsTest" tests="21" failures="5" timestamp="09 Jun 2018 18:54:18 GMT" time="298.739" errors="0">
  <testcase name="saveAdictions" time="57.816" classname="com_Milan_Test.WAddictionsTest">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Record updated successfully!]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Record updated successfully!]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:129)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.WAddictionsTest.saveAdictions(WAddictionsTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- saveAdictions -->
  <testcase name="saveAdictions" time="61.351" classname="com_Milan_Test.WAddictionsTest">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Record updated successfully!]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Record updated successfully!]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:129)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.WAddictionsTest.saveAdictions(WAddictionsTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- saveAdictions -->
  <testcase name="saveAdictions" time="59.816" classname="com_Milan_Test.WAddictionsTest">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Record updated successfully!]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Record updated successfully!]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:129)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.WAddictionsTest.saveAdictions(WAddictionsTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- saveAdictions -->
  <testcase name="saveAdictions" time="59.979" classname="com_Milan_Test.WAddictionsTest">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Record updated successfully!]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Record updated successfully!]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:129)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.WAddictionsTest.saveAdictions(WAddictionsTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- saveAdictions -->
  <testcase name="saveAdictions" time="59.777" classname="com_Milan_Test.WAddictionsTest">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Record updated successfully!]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Record updated successfully!]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:129)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.WAddictionsTest.saveAdictions(WAddictionsTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- saveAdictions -->
  <testcase name="SinceWhenEnableconditionSinceWhenCaffeineAddictionTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SinceWhenEnableconditionSinceWhenCaffeineAddictionTest -->
  <testcase name="CurrentStatusEnableConditionAlkoholTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- CurrentStatusEnableConditionAlkoholTest -->
  <testcase name="SinceWhenEnableconditionSinceWhenMonthForCaffeineAddictionTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SinceWhenEnableconditionSinceWhenMonthForCaffeineAddictionTest -->
  <testcase name="SinceWhenEnableconditionSinceWhenMonthAlkoholTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SinceWhenEnableconditionSinceWhenMonthAlkoholTest -->
  <testcase name="SenceWhenEnableconditionSinceWhenYearAlkoholTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SenceWhenEnableconditionSinceWhenYearAlkoholTest -->
  <testcase name="CurrentStatusEnableConditionCaffeineAddictionTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- CurrentStatusEnableConditionCaffeineAddictionTest -->
  <testcase name="SinceWhenEnableconditionSinceWhenMonthForDrugAdictionTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SinceWhenEnableconditionSinceWhenMonthForDrugAdictionTest -->
  <testcase name="CurrentStatusEnableConditionAdictionTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- CurrentStatusEnableConditionAdictionTest -->
  <testcase name="CurrentStatusEnableConditionSmokeTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- CurrentStatusEnableConditionSmokeTest -->
  <testcase name="SenceWhenEnableconditionSinceWhenDrugAddictionYearTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SenceWhenEnableconditionSinceWhenDrugAddictionYearTest -->
  <testcase name="SenceWhenEnableconditionSinceWhenYearSmokeTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SenceWhenEnableconditionSinceWhenYearSmokeTest -->
  <testcase name="SinceWhenEnableconditionSinceWhenMonthTobocoTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SinceWhenEnableconditionSinceWhenMonthTobocoTest -->
  <testcase name="SenceWhenEnableconditionSinceWhenYearTobacoTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SenceWhenEnableconditionSinceWhenYearTobacoTest -->
  <testcase name="saveNewAdictions" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- saveNewAdictions -->
  <testcase name="CurrentStatusEnableConditionTobacoTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- CurrentStatusEnableConditionTobacoTest -->
  <testcase name="SinceWhenEnableconditionSinceWhenMonthSmokeTest" classname="com_Milan_Test.WAddictionsTest">
    <skipped/>
  </testcase> <!-- SinceWhenEnableconditionSinceWhenMonthSmokeTest -->
</testsuite> <!-- com_Milan_Test.WAddictionsTest -->
