<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="IVF111" name="com_Milan_Test.WInvestigationPageTest" tests="5" failures="0" timestamp="22 Jun 2018 09:10:50 GMT" time="74.801" errors="1">
  <testcase name="Setup" time="67.994" classname="com_Milan_Test.WInvestigationPageTest">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com_milan_POM.HomePage.searchPaient(HomePage.java:258)
	at com_Milan_Test.WInvestigationPageTest.Setup(WInvestigationPageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Setup -->
  <testcase name="IVFPACKAGEARTCyclecountTest" time="6.807" classname="com_Milan_Test.WInvestigationPageTest"/>
  <testcase name="OUIARTSubTypesTest" time="0.000" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- OUIARTSubTypesTest -->
  <testcase name="OPUCycleTest" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- OPUCycleTest -->
  <testcase name="CycleCreationTest" classname="com_Milan_Test.WInvestigationPageTest">
    <skipped/>
  </testcase> <!-- CycleCreationTest -->
</testsuite> <!-- com_Milan_Test.WInvestigationPageTest -->
