<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="IVF111" name="com_Milan_Test.EMRDashBoardPageTest" tests="4" failures="0" timestamp="17 May 2018 05:44:44 GMT" time="32.136" errors="1">
  <testcase name="Seup" time="32.136" classname="com_Milan_Test.EMRDashBoardPageTest">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 3, Size: 3">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com_milan_POM.HomePage.searchPaient(HomePage.java:161)
	at com_Milan_Test.EMRDashBoardPageTest.Seup(EMRDashBoardPageTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Seup -->
  <testcase name="ClickonWoomenPaientFieldTest" time="0.000" classname="com_Milan_Test.EMRDashBoardPageTest">
    <skipped/>
  </testcase> <!-- ClickonWoomenPaientFieldTest -->
  <testcase name="ClickOnMenPaientHistory" time="0.000" classname="com_Milan_Test.EMRDashBoardPageTest">
    <skipped/>
  </testcase> <!-- ClickOnMenPaientHistory -->
  <testcase name="ClickOnDiagnosisTest" time="0.000" classname="com_Milan_Test.EMRDashBoardPageTest">
    <skipped/>
  </testcase> <!-- ClickOnDiagnosisTest -->
</testsuite> <!-- com_Milan_Test.EMRDashBoardPageTest -->
