<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="IVF111" name="com_Milan_Test.FemaleDiagnosisTest" tests="13" failures="2" timestamp="13 May 2018 13:58:34 GMT" time="466.458" errors="0">
  <testcase name="ClickOnOtherDiagnosisTest" time="35.035" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- ClickOnOtherDiagnosisTest -->
  <testcase name="ClickOnOtherDiagnosisTest" time="36.317" classname="com_Milan_Test.FemaleDiagnosisTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Message doesn&#039;t matched expected [Palash IVFRecord saved successfully!] but found [Code already exists]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Message doesn't matched expected [Palash IVFRecord saved successfully!] but found [Code already exists]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com_Milan_Test.FemaleDiagnosisTest.ClickOnOtherDiagnosisTest(FemaleDiagnosisTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- ClickOnOtherDiagnosisTest -->
  <testcase name="ClickOnOtherDiagnosisTest" time="34.846" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- ClickOnOtherDiagnosisTest -->
  <testcase name="ClickOnOtherDiagnosisTest" time="34.502" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- ClickOnOtherDiagnosisTest -->
  <testcase name="CodevalueTest" time="37.780" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- CodevalueTest -->
  <testcase name="CodevalueTest" time="36.479" classname="com_Milan_Test.FemaleDiagnosisTest">
    <failure type="java.lang.AssertionError" message="Codevalue doesn&#039;t matched expected [delete1289] but found [81]">
      <![CDATA[java.lang.AssertionError: Codevalue doesn't matched expected [delete1289] but found [81]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com_Milan_Test.FemaleDiagnosisTest.CodevalueTest(FemaleDiagnosisTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CodevalueTest -->
  <testcase name="CodevalueTest" time="91.311" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- CodevalueTest -->
  <testcase name="CodevalueTest" time="38.492" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- CodevalueTest -->
  <testcase name="AddFavoriteFromListTest" time="39.672" classname="com_Milan_Test.FemaleDiagnosisTest"/>
  <testcase name="UnFavoriteTheFavioriteTest" time="43.097" classname="com_Milan_Test.FemaleDiagnosisTest"/>
  <testcase name="checkboxclickTest" time="38.927" classname="com_Milan_Test.FemaleDiagnosisTest"/>
  <testcase name="DeleteFromFavoriteTest" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- DeleteFromFavoriteTest -->
  <testcase name="TypeSelectionboxEnableconditionForOtherfavorireTest" classname="com_Milan_Test.FemaleDiagnosisTest">
    <skipped/>
  </testcase> <!-- TypeSelectionboxEnableconditionForOtherfavorireTest -->
</testsuite> <!-- com_Milan_Test.FemaleDiagnosisTest -->
