<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="IVF111" name="com_Milan_Test.SimulationChartPageTest" tests="8" failures="1" timestamp="19 Jul 2018 18:16:06 GMT" time="1233.855" errors="0">
  <testcase name="AddDrugNames" time="108.886" classname="com_Milan_Test.SimulationChartPageTest"/>
  <testcase name="EnableconditionAddSimulationDrugTest" time="107.024" classname="com_Milan_Test.SimulationChartPageTest"/>
  <testcase name="SaveSimulationTest" time="115.321" classname="com_Milan_Test.SimulationChartPageTest">
    <skipped/>
  </testcase> <!-- SaveSimulationTest -->
  <testcase name="SaveSimulationTest" time="143.745" classname="com_Milan_Test.SimulationChartPageTest">
    <skipped/>
  </testcase> <!-- SaveSimulationTest -->
  <testcase name="SaveSimulationTest" time="113.981" classname="com_Milan_Test.SimulationChartPageTest">
    <failure type="java.lang.AssertionError" message="expected [Cycle Overview] but found [Stimulation Chart]">
      <![CDATA[java.lang.AssertionError: expected [Cycle Overview] but found [Stimulation Chart]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com_Milan_Test.SimulationChartPageTest.SaveSimulationTest(SimulationChartPageTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- SaveSimulationTest -->
  <testcase name="SaveSimulationTest" time="113.682" classname="com_Milan_Test.SimulationChartPageTest">
    <skipped/>
  </testcase> <!-- SaveSimulationTest -->
  <testcase name="SimulationDrugValidationTest" time="380.198" classname="com_Milan_Test.SimulationChartPageTest"/>
  <testcase name="InvalidDateTest" time="151.018" classname="com_Milan_Test.SimulationChartPageTest"/>
</testsuite> <!-- com_Milan_Test.SimulationChartPageTest -->
